const resultado = {
  "BAHIA MALUCA": [
    {
      "titulo": "10h - MALUCA - Resultado do dia 27/10/2024 (Domingo)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5457",
          "15",
          "Jacaré"
        ],
        [
          "2º",
          "1738",
          "10",
          "Coelho"
        ],
        [
          "3º",
          "6710",
          "03",
          "Burro"
        ],
        [
          "4º",
          "0825",
          "07",
          "Carneiro"
        ],
        [
          "5º",
          "5756",
          "14",
          "Gato"
        ],
        [
          "6º",
          "7900",
          "25",
          "Vaca"
        ],
        [
          "7º",
          "0775",
          "19",
          "Pavão"
        ],
        [
          "8º",
          "0153",
          "14",
          "Gato"
        ],
        [
          "9º",
          "0955",
          "14",
          "Gato"
        ],
        [
          "10º",
          "8096",
          "24",
          "Veado"
        ]
      ]
    },
    {
      "titulo": "12h - MALUCA - BA - Resultado do dia 27/10/2024 (Domingo)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5362",
          "16",
          "Leão"
        ],
        [
          "2º",
          "7816",
          "04",
          "Borboleta"
        ],
        [
          "3º",
          "1218",
          "05",
          "Cachorro"
        ],
        [
          "4º",
          "3540",
          "10",
          "Coelho"
        ],
        [
          "5º",
          "5256",
          "14",
          "Gato"
        ],
        [
          "6º",
          "0269",
          "18",
          "Porco"
        ],
        [
          "7º",
          "1032",
          "08",
          "Camelo"
        ],
        [
          "8º",
          "2483",
          "21",
          "Touro"
        ],
        [
          "9º",
          "3685",
          "22",
          "Tigre"
        ],
        [
          "10º",
          "1510",
          "03",
          "Burro"
        ]
      ]
    },
    {
      "titulo": "15h - MALUCA - BA - Resultado do dia 27/10/2024 (Domingo)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7556",
          "14",
          "Gato"
        ],
        [
          "2º",
          "4015",
          "04",
          "Borboleta"
        ],
        [
          "3º",
          "9556",
          "14",
          "Gato"
        ],
        [
          "4º",
          "2670",
          "18",
          "Porco"
        ],
        [
          "5º",
          "6291",
          "23",
          "Urso"
        ],
        [
          "6º",
          "6558",
          "15",
          "Jacaré"
        ],
        [
          "7º",
          "3715",
          "04",
          "Borboleta"
        ],
        [
          "8º",
          "5073",
          "19",
          "Pavão"
        ],
        [
          "9º",
          "5442",
          "11",
          "Cavalo"
        ],
        [
          "10º",
          "0602",
          "01",
          "Avestruz"
        ]
      ]
    }
  ],
  "BAHIA": [
    {
      "titulo": "10h - BA - Resultado do dia 27/10/2024 (Domingo)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0615",
          "04",
          "Borboleta"
        ],
        [
          "2º",
          "8774",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "2135",
          "09",
          "Cobra"
        ],
        [
          "4º",
          "5087",
          "22",
          "Tigre"
        ],
        [
          "5º",
          "6575",
          "19",
          "Pavão"
        ],
        [
          "6º",
          "0007",
          "02",
          "Águia"
        ],
        [
          "7º",
          "9179",
          "20",
          "Peru"
        ],
        [
          "8º",
          "5570",
          "18",
          "Porco"
        ],
        [
          "9º",
          "5350",
          "13",
          "Galo"
        ],
        [
          "10º",
          "6908",
          "02",
          "Águia"
        ]
      ]
    },
    {
      "titulo": "12h - BA - Resultado do dia 27/10/2024 (Domingo)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3175",
          "19",
          "Pavão"
        ],
        [
          "2º",
          "5283",
          "21",
          "Touro"
        ],
        [
          "3º",
          "4116",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "0862",
          "16",
          "Leão"
        ],
        [
          "5º",
          "6525",
          "07",
          "Carneiro"
        ],
        [
          "6º",
          "3210",
          "03",
          "Burro"
        ],
        [
          "7º",
          "6402",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "8836",
          "09",
          "Cobra"
        ],
        [
          "9º",
          "5329",
          "08",
          "Camelo"
        ],
        [
          "10º",
          "0151",
          "13",
          "Galo"
        ]
      ]
    },
    {
      "titulo": "15h - BA - Resultado do dia 27/10/2024 (Domingo)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2947",
          "12",
          "Elefante"
        ],
        [
          "2º",
          "6505",
          "02",
          "Águia"
        ],
        [
          "3º",
          "7515",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "0656",
          "14",
          "Gato"
        ],
        [
          "5º",
          "1926",
          "07",
          "Carneiro"
        ],
        [
          "6º",
          "5536",
          "09",
          "Cobra"
        ],
        [
          "7º",
          "4075",
          "19",
          "Pavão"
        ],
        [
          "8º",
          "4715",
          "04",
          "Borboleta"
        ],
        [
          "9º",
          "2358",
          "15",
          "Jacaré"
        ],
        [
          "10º",
          "2060",
          "15",
          "Jacaré"
        ]
      ]
    }
  ],
  "LOTECE": [
    {
      "titulo": "Resultado do Jogo do Bicho A FEDERAL DO BRASIL CE - Ceará Federal",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "8966",
          "17",
          "Macaco"
        ],
        [
          "2º",
          "6491",
          "23",
          "Urso"
        ],
        [
          "3º",
          "1106",
          "02",
          "Águia"
        ],
        [
          "4º",
          "3263",
          "16",
          "Leão"
        ],
        [
          "5º",
          "1223",
          "06",
          "Cabra"
        ],
        [
          "6º [soma]",
          "1049",
          "",
          ""
        ],
        [
          "7º [mult]",
          "798",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 11:00 (manhã)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6325",
          "07",
          "Carneiro"
        ],
        [
          "2º",
          "0854",
          "14",
          "Gato"
        ],
        [
          "3º",
          "7097",
          "25",
          "Vaca"
        ],
        [
          "4º",
          "3162",
          "16",
          "Leão"
        ],
        [
          "5º",
          "2702",
          "01",
          "Avestruz"
        ],
        [
          "6º",
          "4605",
          "02",
          "Águia"
        ],
        [
          "7º",
          "1545",
          "12",
          "Elefante"
        ],
        [
          "8º",
          "2174",
          "19",
          "Pavão"
        ],
        [
          "9º",
          "4111",
          "03",
          "Burro"
        ],
        [
          "10º",
          "7746",
          "12",
          "Elefante"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 14:00 (tarde)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4142",
          "11",
          "Cavalo"
        ],
        [
          "2º",
          "2672",
          "18",
          "Porco"
        ],
        [
          "3º",
          "6560",
          "15",
          "Jacaré"
        ],
        [
          "4º",
          "9407",
          "02",
          "Águia"
        ],
        [
          "5º",
          "7131",
          "08",
          "Camelo"
        ],
        [
          "6º",
          "9439",
          "10",
          "Coelho"
        ],
        [
          "7º",
          "6954",
          "14",
          "Gato"
        ],
        [
          "8º",
          "2185",
          "22",
          "Tigre"
        ],
        [
          "9º",
          "5015",
          "04",
          "Borboleta"
        ],
        [
          "10º",
          "4455",
          "14",
          "Gato"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 15:45 (tarde II)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0880",
          "20",
          "Peru"
        ],
        [
          "2º",
          "7981",
          "21",
          "Touro"
        ],
        [
          "3º",
          "5638",
          "10",
          "Coelho"
        ],
        [
          "4º",
          "9933",
          "09",
          "Cobra"
        ],
        [
          "5º",
          "3854",
          "14",
          "Gato"
        ],
        [
          "6º",
          "1762",
          "16",
          "Leão"
        ],
        [
          "7º",
          "1774",
          "19",
          "Pavão"
        ],
        [
          "8º",
          "6511",
          "03",
          "Burro"
        ],
        [
          "9º",
          "4269",
          "18",
          "Porco"
        ],
        [
          "10º",
          "0440",
          "10",
          "Coelho"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTECE - CE, 19:00 (noite)",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4075",
          "19",
          "Pavão"
        ],
        [
          "2º",
          "2909",
          "03",
          "Burro"
        ],
        [
          "3º",
          "2095",
          "24",
          "Veado"
        ],
        [
          "4º",
          "6796",
          "24",
          "Veado"
        ],
        [
          "5º",
          "6659",
          "15",
          "Jacaré"
        ],
        [
          "6º",
          "3350",
          "13",
          "Galo"
        ],
        [
          "7º",
          "1219",
          "05",
          "Cachorro"
        ],
        [
          "8º",
          "8701",
          "01",
          "Avestruz"
        ],
        [
          "9º",
          "4039",
          "10",
          "Coelho"
        ],
        [
          "10º",
          "0437",
          "10",
          "Coelho"
        ]
      ]
    }
  ],
  "LOOK/GOIAS": [
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 07h, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4360",
          "15",
          "Jacaré"
        ],
        [
          "2º",
          "1571",
          "18",
          "Porco"
        ],
        [
          "3º",
          "0457",
          "15",
          "Jacaré"
        ],
        [
          "4º",
          "0705",
          "02",
          "Águia"
        ],
        [
          "5º",
          "4851",
          "13",
          "Galo"
        ],
        [
          "6º [soma]",
          "1944",
          "",
          ""
        ],
        [
          "7º [mult]",
          "849",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOOK - GOIÁS, 07h, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4360",
          "15",
          "Jacaré"
        ],
        [
          "2º",
          "1571",
          "18",
          "Porco"
        ],
        [
          "3º",
          "0457",
          "15",
          "Jacaré"
        ],
        [
          "4º",
          "0705",
          "02",
          "Águia"
        ],
        [
          "5º",
          "4851",
          "13",
          "Galo"
        ],
        [
          "6º",
          "4100",
          "25",
          "Vaca"
        ],
        [
          "7º",
          "3547",
          "12",
          "Elefante"
        ],
        [
          "8º",
          "6750",
          "13",
          "Galo"
        ],
        [
          "9º",
          "0175",
          "19",
          "Pavão"
        ],
        [
          "10º",
          "6516",
          "04",
          "Borboleta"
        ]
      ]
    }
  ],
  "LOTEP": [
    {
      "titulo": "Resultado do Jogo do Bicho PB, Paratodos 09:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "2103",
          "01",
          "Avestruz"
        ],
        [
          "2º",
          "5807",
          "02",
          "Águia"
        ],
        [
          "3º",
          "9365",
          "17",
          "Macaco"
        ],
        [
          "4º",
          "1808",
          "02",
          "Águia"
        ],
        [
          "5º",
          "2775",
          "19",
          "Pavão"
        ],
        [
          "6º",
          "2591",
          "23",
          "Urso"
        ],
        [
          "7º",
          "1838",
          "10",
          "Coelho"
        ],
        [
          "8º",
          "0060",
          "15",
          "Jacaré"
        ],
        [
          "9º",
          "3758",
          "15",
          "Jacaré"
        ],
        [
          "10º",
          "0105",
          "02",
          "Águia"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 10:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0278",
          "20",
          "Peru"
        ],
        [
          "2º",
          "8044",
          "11",
          "Cavalo"
        ],
        [
          "3º",
          "3344",
          "11",
          "Cavalo"
        ],
        [
          "4º",
          "5579",
          "20",
          "Peru"
        ],
        [
          "5º",
          "3790",
          "23",
          "Urso"
        ],
        [
          "6º",
          "0835",
          "09",
          "Cobra"
        ],
        [
          "7º",
          "2035",
          "09",
          "Cobra"
        ],
        [
          "8º",
          "7447",
          "12",
          "Elefante"
        ],
        [
          "9º",
          "8449",
          "13",
          "Galo"
        ],
        [
          "10º",
          "9801",
          "01",
          "Avestruz"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho LOTEP - PB, 12:45",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "5841",
          "11",
          "Cavalo"
        ],
        [
          "2º",
          "2508",
          "02",
          "Águia"
        ],
        [
          "3º",
          "3623",
          "06",
          "Cabra"
        ],
        [
          "4º",
          "3955",
          "14",
          "Gato"
        ],
        [
          "5º",
          "6036",
          "09",
          "Cobra"
        ],
        [
          "6º",
          "5233",
          "09",
          "Cobra"
        ],
        [
          "7º",
          "8569",
          "18",
          "Porco"
        ],
        [
          "8º",
          "4025",
          "07",
          "Carneiro"
        ],
        [
          "9º",
          "1835",
          "09",
          "Cobra"
        ],
        [
          "10º",
          "1625",
          "07",
          "Carneiro"
        ]
      ]
    }
  ],
  "PT RIO": [
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 09:20, PT, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6560",
          "15",
          "Jacaré"
        ],
        [
          "2º",
          "7690",
          "23",
          "Urso"
        ],
        [
          "3º",
          "9416",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "3480",
          "20",
          "Peru"
        ],
        [
          "5º",
          "4577",
          "20",
          "Peru"
        ],
        [
          "6º [soma]",
          "1723",
          "",
          ""
        ],
        [
          "7º [mult]",
          "446",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 09:20, PT, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "6560",
          "15",
          "Jacaré"
        ],
        [
          "2º",
          "7690",
          "23",
          "Urso"
        ],
        [
          "3º",
          "9416",
          "04",
          "Borboleta"
        ],
        [
          "4º",
          "3480",
          "20",
          "Peru"
        ],
        [
          "5º",
          "4577",
          "20",
          "Peru"
        ],
        [
          "6º",
          "6793",
          "24",
          "Veado"
        ],
        [
          "7º",
          "5644",
          "11",
          "Cavalo"
        ],
        [
          "8º",
          "6918",
          "05",
          "Cachorro"
        ],
        [
          "9º",
          "0060",
          "15",
          "Jacaré"
        ],
        [
          "10º",
          "1138",
          "10",
          "Coelho"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 11:00, PTM, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3561",
          "16",
          "Leão"
        ],
        [
          "2º",
          "7579",
          "20",
          "Peru"
        ],
        [
          "3º",
          "0237",
          "10",
          "Coelho"
        ],
        [
          "4º",
          "3043",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "7079",
          "20",
          "Peru"
        ],
        [
          "6º [soma]",
          "1499",
          "",
          ""
        ],
        [
          "7º [mult]",
          "988",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 11:00, PTM, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "3561",
          "16",
          "Leão"
        ],
        [
          "2º",
          "7579",
          "20",
          "Peru"
        ],
        [
          "3º",
          "0237",
          "10",
          "Coelho"
        ],
        [
          "4º",
          "3043",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "7079",
          "20",
          "Peru"
        ],
        [
          "6º",
          "3703",
          "01",
          "Avestruz"
        ],
        [
          "7º",
          "5520",
          "05",
          "Cachorro"
        ],
        [
          "8º",
          "6734",
          "09",
          "Cobra"
        ],
        [
          "9º",
          "1973",
          "19",
          "Pavão"
        ],
        [
          "10º",
          "9429",
          "08",
          "Camelo"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 14:20, PT, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7588",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "4873",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "7025",
          "07",
          "Carneiro"
        ],
        [
          "4º",
          "7081",
          "21",
          "Touro"
        ],
        [
          "5º",
          "9112",
          "03",
          "Burro"
        ],
        [
          "6º [soma]",
          "5679",
          "",
          ""
        ],
        [
          "7º [mult]",
          "976",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 14:20, PT, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "7588",
          "22",
          "Tigre"
        ],
        [
          "2º",
          "4873",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "7025",
          "07",
          "Carneiro"
        ],
        [
          "4º",
          "7081",
          "21",
          "Touro"
        ],
        [
          "5º",
          "9112",
          "03",
          "Burro"
        ],
        [
          "6º",
          "7477",
          "20",
          "Peru"
        ],
        [
          "7º",
          "5800",
          "25",
          "Vaca"
        ],
        [
          "8º",
          "8728",
          "07",
          "Carneiro"
        ],
        [
          "9º",
          "8351",
          "13",
          "Galo"
        ],
        [
          "10º",
          "6035",
          "09",
          "Cobra"
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 16:00, PTV, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0404",
          "01",
          "Avestruz"
        ],
        [
          "2º",
          "8323",
          "06",
          "Cabra"
        ],
        [
          "3º",
          "1280",
          "20",
          "Peru"
        ],
        [
          "4º",
          "7544",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "4897",
          "25",
          "Vaca"
        ],
        [
          "6º [soma]",
          "2448",
          "",
          ""
        ],
        [
          "7º [mult]",
          "362",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho RJ, 16:00, PTV, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "0404",
          "01",
          "Avestruz"
        ],
        [
          "2º",
          "8323",
          "06",
          "Cabra"
        ],
        [
          "3º",
          "1280",
          "20",
          "Peru"
        ],
        [
          "4º",
          "7544",
          "11",
          "Cavalo"
        ],
        [
          "5º",
          "4897",
          "25",
          "Vaca"
        ],
        [
          "6º",
          "0817",
          "05",
          "Cachorro"
        ],
        [
          "7º",
          "4325",
          "07",
          "Carneiro"
        ],
        [
          "8º",
          "0284",
          "21",
          "Touro"
        ],
        [
          "9º",
          "4304",
          "01",
          "Avestruz"
        ],
        [
          "10º",
          "2178",
          "20",
          "Peru"
        ]
      ]
    }
  ],
  "PT SP": [
    {
      "titulo": "Resultado do Jogo do Bicho SP, 08hs - PTSP, 1º ao 5º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4714",
          "04",
          "Borboleta"
        ],
        [
          "2º",
          "2573",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "1070",
          "18",
          "Porco"
        ],
        [
          "4º",
          "4250",
          "13",
          "Galo"
        ],
        [
          "5º",
          "7080",
          "20",
          "Peru"
        ],
        [
          "6º [soma]",
          "9687",
          "",
          ""
        ],
        [
          "7º [mult]",
          "129",
          "",
          ""
        ]
      ]
    },
    {
      "titulo": "Resultado do Jogo do Bicho SP, 08hs - PTSP, 1º ao 10º",
      "conteudo": [
        [
          "Prêmio",
          "Milhar",
          "Grupo",
          "Bicho"
        ],
        [
          "1º",
          "4714",
          "04",
          "Borboleta"
        ],
        [
          "2º",
          "2573",
          "19",
          "Pavão"
        ],
        [
          "3º",
          "1070",
          "18",
          "Porco"
        ],
        [
          "4º",
          "4250",
          "13",
          "Galo"
        ],
        [
          "5º",
          "7080",
          "20",
          "Peru"
        ],
        [
          "6º",
          "4214",
          "04",
          "Borboleta"
        ],
        [
          "7º",
          "7502",
          "01",
          "Avestruz"
        ],
        [
          "8º",
          "1775",
          "19",
          "Pavão"
        ],
        [
          "9º",
          "4300",
          "25",
          "Vaca"
        ],
        [
          "10º",
          "7478",
          "20",
          "Peru"
        ]
      ]
    }
  ]
};